### ISSUE TITLE
Big7 not found

### ISSUE THREAD

**Issue by mpearmain** [Cospel/kaggle-rossmann#1]
I'v erun the create_data and load_data scripts bu tget the following error in trying to run lstm_simple.py

:~/kaggle-rossmann/src/models$ python lstm_simple.py 
Using gpu device 0: Quadro 5000
Loading data ...
Creating simple DLSTM ...
Getting data ...
Traceback (most recent call last):
  File "lstm_simple.py", line 64, in <module>
    x = np.concatenate(np.load('big7x.npy'))
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 362, in load
    fid = open(file, "rb")
IOError: [Errno 2] No such file or directory: 'big7x.npy'
Closing remaining open files:../../data/data.h5...done

**Comment by Cospel** [comment]
Hi,
You can rename file of 'bigXx.npy' manually in create_data.py and get your bigXx.npy sequence. You can specify how long the sequence should be also. In actual version there is big5x.npy with 5 previous sequnce dataset for lstm.

I will try to update the create_data.py.

**Comment by Cospel** [comment]
I update create_data.py and lstm but I get error because of new version of Keras.

```
raise Exception('Layer is not connected. Did you forget to set "input_shape"?')
```

**Comment by mpearmain** [comment]
I get the same error.

Will look as well
